# Codecov Configuration
# Aligned with Jest layered coverage thresholds in jest.config.js

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2% # Allow 2% drop from base
    patch:
      default:
        target: 50% # New code should aim for 50% coverage minimum
        threshold: 5% # Allow 5% tolerance

  # Ignore files that are hard to unit test (infra boundary, middleware)
ignore:
  - 'src/middleware.ts'
  - 'src/infrastructure/auth/**'


comment:
  layout: 'reach,diff,flags,files'
  behavior: default
  require_changes: false
